.TH CLDAP_SETRETRYINFO 3 "22 September 1998" "OpenLDAP LDVERSION"
.\" $OpenLDAP$
.\" Copyright 1998-1999 The OpenLDAP Foundation All Rights Reserved.
.\" Copying restrictions apply.  See COPYRIGHT/LICENSE.
.SH NAME
cldap_setretryinfo \- Set Connectionless LDAP Request Retransmission Parameters
.SH SYNOPSIS
.nf
.ft B
#include <lber.h>
#include <ldap.h>
.LP
.ft B
void cldap_setretryinfo(ld, tries, timeout)
.ft
LDAP *ld;
int tries;
int timeout;
.SH DESCRIPTION
.LP
The
.B cldap_setretryinfo()
routine is used to set the CLDAP
request retransmission behavior for future
.BR cldap_search_s (3)
calls.
.LP
.B cldap_setretryinfo()
takes \fIld\fP, the LDAP pointer returned from a
previous call to
.BR cldap_open (3),
\fItries\fP, the maximum number of
times to send a request, and \fItimeout\fP, the initial time, in
seconds, to wait before re-sending a request.  The default values (set by
.BR cldap_open (3))
are 4 tries and 3 seconds between tries.  See
.BR cldap_search_s (3)
for a complete description of the retransmission
algorithm used.
.LP
.SH SEE ALSO
.BR ldap (3),
.BR cldap_open (3),
.BR cldap_search_s (3),
.BR cldap_close (3)
.SH ACKNOWLEDGEMENTS
.B	OpenLDAP
is developed and maintained by The OpenLDAP Project (http://www.openldap.org/).
.B	OpenLDAP
is derived from University of Michigan LDAP 3.3 Release.  
