.TH LDAP_ABANDON 3 "RELEASEDATE" "OpenLDAP LDVERSION"
.\" $OpenLDAP$
.\" Copyright 1998-2008 The OpenLDAP Foundation All Rights Reserved.
.\" Copying restrictions apply.  See COPYRIGHT/LICENSE.
.SH NAME
ldap_abandon, ldap_abandon_ext \- Abandon an LDAP operation in progress
.SH LIBRARY
OpenLDAP LDAP (libldap, -lldap)
.SH SYNOPSIS
.nf
.B #include <ldap.h>
.sp
.BI "int ldap_abandon(LDAP *" ld ", int " msgid ");"
.sp
.BI "int ldap_abandon_ext(LDAP *" ld ", int " msgid ","
.RS
.BI "LDAPControl *" sctrls "[], LDAPControl *" cctrls "[]);"
.RE
.fi
.SH DESCRIPTION
The
.B ldap_abandon()
routine is used to abandon or cancel an LDAP
operation in progress.  The \fImsgid\fP passed should be the
message id of an outstanding LDAP operation, as returned by
.BR ldap_search (3),
.BR ldap_modify (3),
etc.
.LP
.BR ldap_abandon ()
checks to see if the result of the operation has already come in.  If it
has, it deletes it from the queue of pending messages.  If not,
it sends an LDAP abandon operation to the the LDAP server.
.LP
The caller can expect that the result of an abandoned operation
will not be returned from a future call to
.BR ldap_result (3).
.LP
.B ldap_abandon_ext()
is equivalent to
.B ldap_abandon()
except that it allows server and client controls to be passed
in
.I sctrls
and
.IR cctrls ,
respectively.
.SH ERRORS
.B ldap_abandon()
returns 0 if everything goes ok, -1 otherwise,
setting \fIld_errno\fP with an appropriate LDAP error code.
.LP
.B ldap_abandon_ext()
directly returns an LDAP error code indicating success or failure of the
operation.
.LP
See
.BR ldap_error (3)
for details.
.SH SEE ALSO
.BR ldap (3),
.BR ldap_result (3),
.BR ldap_error (3)
.SH ACKNOWLEDGEMENTS
.B OpenLDAP
is developed and maintained by The OpenLDAP Project (http://www.openldap.org/).
.B OpenLDAP
is derived from University of Michigan LDAP 3.3 Release.  
