.TH LDAP_ADD 3 "22 September 1998" "OpenLDAP LDVERSION"
.\" $OpenLDAP$
.\" Copyright 1998-1999 The OpenLDAP Foundation All Rights Reserved.
.\" Copying restrictions apply.  See COPYRIGHT/LICENSE.
.SH NAME
ldap_add, ldap_add_s \- Perform an LDAP add operation
.SH SYNOPSIS
.nf
.ft B
#include <ldap.h>
.LP
.ft B
int ldap_add(ld, dn, attrs)
.ft
LDAP *ld;
char *dn;
LDAPMod *attrs[];
.LP
.ft B
int ldap_add_s(ld, dn, attrs)
.ft
LDAP *ld;
char *dn;
LDAPMod *attrs[];
.SH DESCRIPTION
The
.B ldap_add_s()
routine is used to perform an LDAP add operation.
It takes \fIdn\fP, the DN of the entry to add, and \fIattrs\fP, a
null-terminated array of the entry's attributes.  The LDAPMod structure
is used to represent attributes, with the \fImod_type\fP and
\fImod_values\fP fields being used as described under
.BR ldap_modify (3),
and the \fIldap_op\fP field being used only if you need to specify
the LDAP_MOD_BVALUES option. Otherwise, it should be set to zero.
.LP
Note that all entries except that
specified by the last component in the given DN must already exist.
.B ldap_add_s()
returns an LDAP error code indicating success or failure
of the operation.  See
.BR ldap_error (3)
for more details.
.LP
The
.B ldap_add()
routine works just like
.BR ldap_add_s() ,
but it is asynchronous.  It returns the message id of the request it
initiated.  The result of this operation can be obtained by calling
.BR ldap_result (3).
.SH ERRORS
.B ldap_add()
returns -1 in case of error initiating the request, and
will set the \fIld_errno\fP field in the \fIld\fP parameter
to indicate the error.
.B ldap_add_s()
will return an LDAP error code
directly (LDAP_SUCCESS if everything went ok, some error otherwise).
.SH SEE ALSO
.BR ldap(3),
.B ldap_modify(3)
.SH ACKNOWLEDGEMENTS
.B	OpenLDAP
is developed and maintained by The OpenLDAP Project (http://www.openldap.org/).
.B	OpenLDAP
is derived from University of Michigan LDAP 3.3 Release.  
