.TH LDBMCAT 8C "13 November 1995" "U-M LDAP LDVERSION"
.SH NAME
ldbmcat \- LDBM to LDIF database format conversion utility
.SH SYNOPSIS
.B SBINDIR/ldbmcat [\-n] id2entry\-file
.LP
.SH DESCRIPTION
.LP
This program is used to convert a
.BR slapd (8)
LDBM database to the text LDAP Directory Interchange Format (LDIF).
It opens the given
.I id2entry\-file
and writes the corresponding LDIF output to standard output.
.LP
See "The SLAPD and SLURPD Administrator's Guide" for more details on
using this program.
.SH OPTIONS
.TP
.B \-n
This option specifies that
.B ldbmcat
should not print entry IDs when it dumps out the database. Note
that the printing of entry IDs is essential if you are going to
use the LDIF format produced as input to
.B ldif2index,
for example, to create a new index file for use with an existing
database.
.SH EXAMPLES
To make a text backup of your LDBM database and put it in a file called
.BR ldif ,
give the command:
.LP
.nf
.ft tt
	SBINDIR/ldbmcat -n id2entry.dbb > ldif
.ft
.fi
.LP
To create a new index for the
.B mail
attribute, give these commands:
.LP
.nf
.ft tt
	SBINDIR/ldbmcat id2entry.dbb > ldif
	SBINDIR/ldif2index -i ldif -f slapd-config-file mail
.ft
.fi
.LP
Note that your
.B slapd (8)
should not be running (at least, not in read-write
mode) when you do this to ensure consistency of the database.
.SH "SEE ALSO"
.BR ldap (3),
.BR ldif (5),
.BR ldif2ldbm (8),
.BR slapd (8)
.LP
"The SLAPD and SLURPD Administrator's Guide"
