.TH SLAPPASSWD 8C "20 August 2000" "OpenLDAP LDVERSION"
.\" $OpenLDAP$
.\" Copyright 1998-2000 The OpenLDAP Foundation All Rights Reserved.
.\" Copying restrictions apply.  See COPYRIGHT/LICENSE.
.SH NAME
slappasswd \- OpenLDAP password utility
.SH SYNOPSIS
.B SBINDIR/slappasswd
.B [\-u]
.B [\-v]
.B [\-s secret]
.B [\-h hash]
.B 
.LP
.SH DESCRIPTION
.LP
.B Slappasswd
is used to generate an authPassword (or userPassword) value
suitable for use with
.BR ldapmodify (1)
or
.BR slapd.conf (5)
.I rootpw
coniguration directive.
.SH OPTIONS
.TP
.B \-u
generate RFC2307 userPassword values instead of authPassword values.
.TP
.B \-v
enable verbose mode.
.TP
.BI \-s " secret"
The secret to hash.  If not provided, the user will be prompted
for the secret to hash.
.TP
.BI \-h " scheme"
The hash scheme to use.  One of the following authPassword schemes
may be specified:
.IR MD5 ,
.IR SHA1 ", and"
.IR X-CRYPT .
The default is
.IR SHA1 .
If -u is specified, one of the following RFC2307 schemes may
be specified:
.IR {CRYPT} ,
.IR {MD5} ,
.IR {SMD5} ,
.IR {SSHA} ", and"
.IR {SHA} .
The default is 
.IR {SSHA} .
.LP
.SH LIMITATIONS
The authPassword attribute type is not yet widely supported.
The practice storing hashed passwords in userPassword violates
Standard Track schema and may hinder interoperability.  
.SH "SECURITY CONSIDERATIONS"
Use of hashed passwords does not protect passwords during
protocol transfer.  TLS or other eavesdropping protections
should be inplace before using LDAP simple bind.  The
hashed password values should be protected as if they
were clear text passwords.
.SH "SEE ALSO"
.BR ldappasswd (1),
.BR ldapmodify (1),
.BR slapd (8)
.BR slapd.conf (5)
.LP
"OpenLDAP Administrator's Guide" (http://www.OpenLDAP.org/doc/admin/)
.SH ACKNOWLEDGEMENTS
OpenLDAP is developed and maintained by
The OpenLDAP Project (http://www.openldap.org/).
OpenLDAP is derived from University of Michigan LDAP 3.3 Release.  
