/*
	File:		GetMyIPAddr.h

	Copyright:	© 1984-1993 by Apple Computer, Inc., all rights reserved.

	WARNING
	This file was auto generated by the interfacer tool. Modifications
	must be made to the master file.

*/

#ifndef __GETMYIPADDR__
#define __GETMYIPADDR__

#ifndef __MACTCPCOMMONTYPES__
#include <MacTCPCommonTypes.h>
#endif

#define ipctlGetAddr 15			/* csCode to get our IP address */

#define GetIPParamBlockHeader 	\
	struct QElem *qLink; 		\
	short qType; 				\
	short ioTrap; 				\
	Ptr ioCmdAddr; 				\
	ProcPtr ioCompletion; 		\
	OSErr ioResult; 			\
	StringPtr ioNamePtr; 		\
	short ioVRefNum;			\
	short ioCRefNum;			\
	short csCode

#if defined(powerc) || defined (__powerc)
#pragma options align=mac68k
#endif
struct GetAddrParamBlock {
	GetIPParamBlockHeader;		/* standard I/O header */	
	ip_addr		ourAddress;		/* our IP address */
	long		ourNetMask;		/* our IP net mask */
};
#if defined(powerc) || defined(__powerc)
#pragma options align=reset
#endif

#endif

