.TH LDAP.CONF 5 "29 November 1998" "OpenLDAP LDVERSION"
.UC 6
.SH NAME
ldap.conf \- ldap configuration file
.SH SYNOPSIS
ETCDIR/ldap.conf
.SH DESCRIPTION
The
.I ldap.conf
configuration file is used to set system-wide defaults to be applied when
running
.I ldap
clients.  If the environment variable \fBLDAPNOINIT\fP is defined, all
defaulting is disabled.
.LP
Each user may specify an optional configuration file,
.IR .ldaprc ,
in his/her home directory which will be used to override the system-wide
defaults file.
.LP
Additional configuration files can be specified using
the \fBLDAPCONF\fP and \fBLDAPRC\fP environment variables.
\fBLDAPCONF\fP may be set the path of a configuration file.  This
path can be absolute or relative to current working directory.
The \fBLDAPRC\fP, if defined, should be a basename of a file
in the current working directory or in the user's home directory.
.LP
Environmental variables may also be used to augment the file based defaults.
The name of the option is the as listed but with a prefix of \fBLDAP\fP.
For example, to define \fBBASE\fP via the environment, define the variable
\fBLDAPBASE\fP to desired value.
.SH OPTIONS
The different configuration options are:
.TP 1i
\fBBASE <base>\fP
Used to specify the default base dn to use when performing ldap operations.
The base must be specified as a Distinguished Name in LDAP format.
.TP 1i
\fBHOST <name[:port] ...>\fP
Used to specify the name(s) of an LDAP server(s) to which 
.I ldap 
library should connect to.  Each server's name can be specified as a
domain-style name or an IP address and optionally followed a ':' and
the port number the ldap server is listening on.  A space separated
listed of host may be provided.
.TP 1i
\fBPORT <port>\fP
Used to specify the port used with connecting to LDAP servers(s).
The port may be specified as a number.
.TP 1i
\fBSIZELIMIT <integer>\fP
Used to specify a size limit to use when performing searches.  The
number should be an non-negative integer.  \fISIZELIMIT\fP of zero (0)
specifies unlimited search size.
.TP 1i
\fBTIMELIMIT <integer>\fP
Used to specify a time limit to use when performing searches.  The
number should be an non-negative integer.  \fITIMELIMIT\fP of zero (0)
specifies unlimited search time to be used.
.TP 1i
\fBDEREF <never|searching|finding|always>\fP
Specify how aliases dereferencing is done.  \fIDEREF\fP should
be set to one of
.B never,
.B always,
.B search,
or 
.B find 
to specify that aliases are never dereferenced, always dereferenced,
dereferenced when searching, or dereferenced only when locating the
base object for the search.  The default is to never dereference aliases.
.SH FILES
.I  ETCDIR/ldap.conf
.LP
.I  $HOME/.ldaprc
.LP
.I  $CWD/.ldaprc
.SH "SEE ALSO"
ldap(3)
.SH AUTHOR
Kurt Zeilenga, The OpenLDAP Project
.SH ACKNOWLEDGEMENTS
.B	OpenLDAP
is developed and maintained by The OpenLDAP Project (http://www.openldap.org/).
.B	OpenLDAP
is derived from University of Michigan LDAP 3.3 Release.  
