.TH LDAPFRIENDLY 5 "22 September 1998" "OpenLDAP LDVERSION"
.\" $OpenLDAP$
.\" Copyright 1998-2000 The OpenLDAP Foundation All Rights Reserved.
.\" Copying restrictions apply.  See COPYRIGHT/LICENSE.
.SH NAME
ldapfriendly \- data file for LDAP friendly routines
.SH SYNOPSIS
DATADIR/ldapfriendly
.SH DESCRIPTION
.LP
The file DATADIR/ldapfriendly contains simple mapping information
used by the
.BR ldap_friendly_name (3)
routine.  Blank lines and
lines that have a first character of `#' are treated as comments and
ignored.  The information consists of lines that contain
an "unfriendly" name, a tab, and a "friendly" name.
.LP
Other friendly mapping files can be created and used by
.BR ldap_friendly_name (3).
Just use the same format as that described
above and include the file name in the
.B ldap_friendly_name()
call.
.SH FILES
DATADIR/ldapfriendly
.SH SEE ALSO
.BR ldap (3),
.BR ldap_friendly_name (3)
.SH ACKNOWLEDGEMENTS
.B	OpenLDAP
is developed and maintained by The OpenLDAP Project (http://www.openldap.org/).
.B	OpenLDAP
is derived from University of Michigan LDAP 3.3 Release.  
