extern  int bind_info(void);
extern  int auth(char *who,char *best_guess);
extern  char *mygetpass(char *prompt);
extern  int iam(char *who);
extern  int print_my_name(void);
extern  int init_search(char * *attributes);
extern  int init_read(char * *attributes);
extern  int dxi_vrfy(char *dn);
extern  LDAPMessage *find(char *who);
extern  int pick_one(int i);
extern  int print_list(LDAPMessage *list,char * *names,int *matches);
extern  int main(int argc,char * *argv);
extern  int do_commands(void);
extern  int status(void);
extern  int change_base(char *s);
extern  int initialize_client(void);
extern  int attn(void);
extern  int print_help(char *s);
extern  char *alias(char *s);
extern  void printbase(char *lead,char *s);
extern  int fetch_buffer(char *buffer,int length,struct _iobuf *where);
extern  int modify(char *who);
extern  void set_pw(char *who);
extern  int change_field(char *tag,char *id,char (*val)[256],char *who);
extern  char *get_value(char *id,char *prompt);
extern  int parse_answer(LDAPMessage *s);
extern  int print_person(void);
extern  int print_entry(char (*s)[256],char *label);
