#! /bin/sh
# $OpenLDAP$

# disable LDAP initialization
LDAPNOINIT=true; export LDAPNOINIT

echo ">>>>> Executing all LDAP tests..."

if test $# -eq 0 ; then
	SRCDIR="."
else
	SRCDIR=$1; shift
fi

echo ">>>>> Test Directory: $SRCDIR"

if test $# -eq 0 ; then
	BACKEND=bdb
else
	BACKEND=$1; shift
fi

echo ">>>>> Backend: $BACKEND"

if test $# -eq 0 ; then
	BACKENDTYPE=yes
else
	BACKENDTYPE=$1; shift
fi

echo ">>>>> Backend Type: $BACKENDTYPE"

if test $# -eq 0 ; then
	MONITOR=no
else
	MONITOR=$1; shift
fi

SHTOOL="$SRCDIR/../build/shtool"

if test $# -eq 0 ; then
	PROXYCACHE=no
else
	PROXYCACHE=$1; shift
fi

TB=`$SHTOOL echo -e "%B"`
TN=`$SHTOOL echo -e "%b"`

for CMD in $SRCDIR/scripts/test*; do
	echo ">>>>> Starting ${TB}`basename $CMD`${TN} ..."
	$CMD $SRCDIR $BACKEND $BACKENDTYPE $MONITOR $PROXYCACHE
	RC=$?
	if test $RC -eq 0 ; then
		echo ">>>>> $CMD completed ${TB}OK${TN}."
	else
		echo ">>>>> $CMD ${TB}failed${TN} (exit $RC)"
		exit $RC
	fi
	echo ">>>>> waiting 10 seconds for things to exit"
	sleep 10
	echo ""
done
