#! /bin/sh
# $OpenLDAP$

SHTOOL="$SRCDIR/../build/shtool"
TB=`$SHTOOL echo -e "%B"`
TN=`$SHTOOL echo -e "%b"`

echo ">>>>> Executing all LDAP tests for $BACKEND"

for CMD in $SRCDIR/scripts/test*; do
	# remove cruft from prior test
	/bin/rm -rf test-db test-db1 test-db2
	/bin/rm -rf test-repl test-repl1 test-repl2

	echo ">>>>> Starting ${TB}`basename $CMD`${TN} ..."
	$CMD
	RC=$?
	if test $RC -eq 0 ; then
		echo ">>>>> $CMD completed ${TB}OK${TN}."
	else
		echo ">>>>> $CMD ${TB}failed${TN} (exit $RC)"
		exit $RC
	fi

	echo ">>>>> waiting 10 seconds for things to exit"
	sleep 10
	echo ""
done
