#!/bin/sh

if [ $# -eq 0 ]; then
	SRCDIR="."
else
	SRCDIR=$1; shift
fi
if [ $# -eq 1 ]; then
	BDB2=$1; shift
fi

echo "running defines.sh $SRCDIR $BDB2"

. $SRCDIR/scripts/defines.sh $SRCDIR $BDB2

echo "Datadir is $DATADIR"

echo "Cleaning up in $DBDIR..."

rm -f $DBDIR/[!C]*

echo "Running ldif2ldbm to build slapd database..."
$LDIF2LDBM -f $CONF -i $LDIF -e ../servers/slapd/tools
RC=$?
if [ $RC != 0 ]; then
	echo "ldif2ldbm failed!"
	exit $RC
fi

echo "Waiting 5 seconds for ldif2ldbm to build slapd database..."
sleep 5

echo "Starting slapd on TCP/IP port $PORT..."
$SLAPD -f $CONF -p $PORT -d $LVL $TIMING > $MASTERLOG 2>&1 &
PID=$!

echo "Waiting 5 seconds for slapd to start..."
sleep 5

echo "Using tester for concurrent server access..."
$SLAPDTESTER -b "$BASEDN" -P "$PROGDIR" -d "$DATADIR" -h localhost -p $PORT -D "$MANAGERDN" -w $PASSWD -l 50
RC=$?

if [ $RC != 0 ]; then
	echo "slapd-tester failed!"
	exit $RC
fi 

echo "Using ldapsearch to retrieve all the entries..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
			'objectClass=*' > $SEARCHOUT 2>&1
RC=$?

kill -HUP $PID

if [ $RC != 0 ]; then
	echo "ldapsearch failed!"
	exit $RC
fi

echo "Comparing retrieved entries to LDIF file used to create database"
cmp $SEARCHOUT $LDIF
if [ $? != 0 ]; then
	echo "comparison failed - database was not created correctly"
	exit 1
fi

echo ">>>>> Test succeeded"


exit 0
