#! /bin/sh
# $OpenLDAP$

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

mkdir -p $TESTRUN $DBDIR1

echo "Starting slapd on TCP/IP port $PORT1..."
. $CONFFILTER $BACKEND $MONITORDB < $SCHEMACONF > $CONF1
$SLAPD -f $CONF1 -h $URI1 -d $LVL $TIMING > $LOG1 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi
KILLPIDS="$PID"

echo "Using ldapsearch to retrieve the root DSE..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -b "" -s base -h $LOCALHOST -p $PORT1 '+extensibleObject' > $SEARCHOUT 2>&1
	RC=$?
	if test $RC = 0 ; then
		break
	fi
	echo "Waiting 5 seconds for slapd to start..."
	sleep 5
done

if test $RC = 0 -a $MONITORDB = yes ; then
	echo "Using ldapsearch to retrieve the cn=Monitor..."
	$LDAPSEARCH -b "cn=Monitor" -s base -h $LOCALHOST -p $PORT1 '+extensibleObject' >> $SEARCHOUT 2>&1
	RC=$?
fi

test $KILLSERVERS != no && kill -HUP $KILLPIDS

cat $SEARCHOUT

if test $RC != 0 ; then
	echo ">>>>> Test failed"
else
	if grep "TLS:" $SEARCHOUT; then
		RC=-1
	else
	    echo ">>>>> Test succeeded"
	fi
fi

exit $RC
