#! /bin/sh
# $OpenLDAP$
## This work is part of OpenLDAP Software <http://www.openldap.org/>.
##
## Copyright 1998-2004 The OpenLDAP Foundation.
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted only as authorized by the OpenLDAP
## Public License.
##
## A copy of this license is available in the file LICENSE in the
## top-level directory of the distribution or, alternatively, at
## <http://www.OpenLDAP.org/license.html>.

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

if test $RWM = rwmno ; then 
	echo "Rewrite/remap overlay not available, test skipped"
	exit 0
fi 

echo ""

RELAYS=
# back-relay
if test $BACKRELAY = relayno ; then 
	echo "relay backend not available, test skipped"
else
	RELAYS="$RELAYS relay"
fi

# back-ldap
if test $BACKLDAP = ldapno ; then 
	echo "ldap backend not available, test skipped"
else
	RELAYS="$RELAYS ldap"
fi

# back-meta
if test $BACKMETA = metano ; then 
	echo "meta backend not available, test skipped"
else
	RELAYS="$RELAYS meta"
fi 

first=1
for RELAY in $RELAYS ; do
	if test $first = 1 ; then
		first=0
	else
		echo ">>>>> waiting 10 seconds for things to exit"
		sleep 10
		echo ""

		rm -rf $TESTDIR
	fi

	mkdir -p $TESTDIR $DBDIR1

	. $SRCDIR/scripts/relay
done

echo ">>>>> Test succeeded"
exit 0

