#!/bin/sh

. scripts/defines.sh


echo "Cleaning up in $DBDIR..."

rm -f $DBDIR/[^C]*

echo "Starting slapd on TCP/IP port $PORT..."
$SLAPD -f $CONF -p $PORT -d 1 > $MASTERLOG 2>&1 &
PID=$!

echo "Using ldapsearch to check that slapd is running..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -L -b "$BASEDN" -h localhost -p $PORT \
		'cn=Monitor' > /dev/null 2>&1
	RC=$?
	if [ $RC = 1 ]; then
		echo "Waiting 5 seconds for slapd to start..."
		sleep 5
	fi
done

echo "Using ldapmodify to populate the database..."
$LDAPMODIFY -a -D "$MANAGERDN" -h localhost -p $PORT -w $PASSWD < \
	$LDIFORDERED > /dev/null 2>&1
RC=$?
if [ $RC != 0 ]; then
	echo "ldapmodify failed!"
	kill -HUP $PID
	exit $RC
fi

echo "Using ldapsearch to read all the entries..."
$LDAPSEARCH -L -S "" -b "$BASEDN" -h localhost -p $PORT \
	'objectclass=*' | egrep -iv '^creatorsname:|^createtimestamp:' > \
	$SEARCHOUT 2>&1

kill -HUP $PID

if [ $RC != 0 ]; then
	echo "ldapsearch failed!"
	exit $RC
fi

echo "Comparing retrieved entries to LDIF file used to create database"
cmp $SEARCHOUT $LDIF
if [ $? != 0 ]; then
	echo "comparison failed - database was not created correctly"
	exit 1
fi

echo ">>>>> Test succeeded"


exit 0
