#! /bin/sh
# $OpenLDAP$

SRCDIR="."
if test $# -ge 1 ; then
	SRCDIR=$1; shift
fi
BACKEND=bdb
if test $# -ge 1 ; then
	BACKEND=$1; shift
fi
MONITORDB=no
if test $# -ge 1 ; then
	MONITORDB=$1; shift
fi

WAIT=0
if test $# -ge 1 ; then
	WAIT=1; shift
fi

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

echo "Datadir is $DATADIR"

echo "Cleaning up in $DBDIR..."

rm -f $DBDIR/[!C]*

echo "Starting slapd on TCP/IP port $PORT..."
. $CONFFILTER $BACKEND $MONITORDB < $SCHEMACONF > $DBCONF
$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi

echo "Using ldapsearch to retrieve the root DSE..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -b "" -s base -h $LOCALHOST -p $PORT 'extensibleObject' > $SEARCHOUT 2>&1
	RC=$?
	if test $RC = 0 ; then
		break
	fi
	echo "Waiting 5 seconds for slapd to start..."
	sleep 5
done

if test $RC = 0 -a $MONITORDB = yes ; then
	echo "Using ldapsearch to retrieve the cn=Monitor..."
	$LDAPSEARCH -b "cn=Monitor" -s base -h $LOCALHOST -p $PORT 'extensibleObject' >> $SEARCHOUT 2>&1
	RC=$?
fi

kill -HUP $PID

cat $SEARCHOUT

if test $RC != 0 ; then
	echo ">>>>> Test failed"
else
	if grep "TLS:" $SEARCHOUT; then
		RC=-1
	else
	    echo ">>>>> Test succeeded"
	fi
fi


exit $RC
