#! /bin/sh
# $OpenLDAP$

SRCDIR="."
if test $# -ge 1 ; then
	SRCDIR=$1; shift
fi
BACKEND=ldbm
if test $# -ge 1 ; then
	BACKEND=$1; shift
fi

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

echo "Cleaning up in $DBDIR..."

rm -f $DBDIR/[!C]*

echo "Running slapadd to build slapd database..."
. $CONFFILTER $BACKEND < $MCONF > $ADDCONF
$SLAPADD -f $ADDCONF -l $LDIFORDERED
RC=$?
if test $RC != 0 ; then
	echo "slapadd failed ($RC)!"
	exit $RC
fi

echo "Running slapindex to index slapd database..."
. $CONFFILTER $BACKEND < $CONF > $DBCONF
$SLAPINDEX -f $DBCONF
RC=$?
if test $RC != 0 ; then
	echo "warning: slapindex failed ($RC)"
	echo "  assuming no indexing support"
fi

echo "Starting slapd on TCP/IP port $PORT..."
$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
PID=$!

echo "Testing slapd searching..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -s base -b "$MONITOR" -h localhost -p $PORT \
		'objectclass=*' > /dev/null 2>&1
	RC=$?
	if test $RC = 1 ; then
		echo "Waiting 5 seconds for slapd to start..."
		sleep 5
	fi
done

if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

cat /dev/null > $SEARCHOUT

echo "Testing exact searching..."
$LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
	'sn=jensen' >> $SEARCHOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

echo "Testing OR searching..."
$LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
	'(|(objectclass=groupofnames)(sn=jones))' >> $SEARCHOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

echo "Testing AND matching and ends-with searching..."
$LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
	'(&(objectclass=groupofnames)(cn=A*))' >> $SEARCHOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

echo "Testing NOT searching..."
$LDAPSEARCH -S "" -b "$BASEDN" -h localhost -p $PORT \
	'(!(objectclass=person))' >> $SEARCHOUT 2>&1
if test $RC != 0 ; then
	echo "ldapsearch failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

kill -HUP $PID

LDIF=$SEARCHOUTMASTER

echo "Filtering ldapsearch results..."
. $LDIFFILTER < $SEARCHOUT > $SEARCHFLT
echo "Filtering original ldif used to create database..."
. $LDIFFILTER < $LDIF > $LDIFFLT
echo "Comparing filter output..."
$CMP $SEARCHFLT $LDIFFLT > $CMPOUT

if test $? != 0 ; then
	echo "Comparison failed"
	exit 1
fi

echo ">>>>> Test succeeded"


exit 0
