#! /bin/sh
# $OpenLDAP$

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

mkdir $DBDIR

echo "Starting slapd on TCP/IP port $PORT..."
. $CONFFILTER $BACKEND $MONITORDB < $PWCONF > $DBCONF
$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
PID=$!
if test $WAIT != 0 ; then
    echo PID $PID
    read foo
fi

echo "Using ldapsearch to check that slapd is running..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -s base -b "$MONITOR" -h $LOCALHOST -p $PORT \
		'objectclass=*' > /dev/null 2>&1
	RC=$?
	if test $RC = 0 ; then
		break
	fi
	echo "Waiting 5 seconds for slapd to start..."
	sleep 5
done

echo "Using ldapadd to populate the database..."
$LDAPADD -D "$MANAGERDN" -h $LOCALHOST -p $PORT -w $PASSWD < \
	$LDIFPASSWD > $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldapadd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

echo > $SEARCHOUT
echo > $TESTOUT

echo "Using ldapsearch to verify population ..."
echo "++ Initial search" >> $SEARCHOUT
$LDAPSEARCH -h $LOCALHOST -p $PORT \
	-D "$MANAGERDN" -w $PASSWD \
	-b "$BASEDN" \
	'objectclass=*' >> $SEARCHOUT 2>&1

echo "Using ldappasswd (PASS 1)  ..."
echo "Pass 1" >> $TESTOUT
$LDAPPASSWD -h $LOCALHOST -p $PORT \
	-w secret -s newsecret \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT \
	-w $PASSWD -s newsecret \
	-D "$MANAGERDN" "cn=smd5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT \
	-w secret -s newsecret \
	-D "cn=sha, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT \
	-w secret -s newsecret \
	-D "cn=ssha, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

echo "" >> $TESTOUT
echo "Pass 2" >> $TESTOUT
echo "Using ldappasswd (PASS 2)  ..."
$LDAPPASSWD -h $LOCALHOST -p $PORT \
	-w newsecret \
	-D "cn=md5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT \
	-w newsecret \
	-D "cn=smd5, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT \
	-w newsecret \
	-D "cn=sha, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi
$LDAPPASSWD -h $LOCALHOST -p $PORT \
	-w newsecret \
	-D "cn=ssha, $BASEDN" >> $TESTOUT 2>&1
RC=$?
if test $RC != 0 ; then
	echo "ldappasswd failed ($RC)!"
	kill -HUP $PID
	exit $RC
fi

kill -HUP $PID

echo ">>>>> Test succeeded"
exit 0
