#! /bin/sh
# $OpenLDAP$

SRCDIR="."
if test $# -ge 1 ; then
	SRCDIR=$1; shift
fi
BACKEND=ldbm
if test $# -ge 1 ; then
	BACKEND=$1; shift
fi

echo "running defines.sh"
. $SRCDIR/scripts/defines.sh

echo "Datadir is $DATADIR"

echo "Cleaning up in $DBDIR..."

rm -f $DBDIR/[!C]*

echo "Starting slapd on TCP/IP port $PORT..."
. $CONFFILTER $BACKEND < $SCHEMACONF > $DBCONF
$SLAPD -f $DBCONF -h $MASTERURI -d $LVL $TIMING > $MASTERLOG 2>&1 &
PID=$!

echo "Using ldapsearch to retrieve all the entries..."
for i in 0 1 2 3 4 5; do
	$LDAPSEARCH -b "" -s base -h localhost:$PORT '+' > $SEARCHOUT 2>&1
	RC=$?
	if test $RC = 1 ; then
		echo "Waiting 5 seconds for slapd to start..."
		sleep 5
	fi
done

kill -HUP $PID

cat $SEARCHOUT

if test $RC != 0 ; then
	echo ">>>>> Test failed"
else
	if grep "TLS:" $SEARCHOUT; then
		RC=-1
	else
	    echo ">>>>> Test succeeded"
	fi
fi


exit $RC
